title: Tim Ehrensperger # your name (or website title) here
logo: "/images/01-Ehrensperger_Tim.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  I am a Master’s student in Data Science at ETH Zurich. My broad interests have led me to explore fields such as journalism and pursue a minor in astronomy. I am particularly interested in making an impact in areas like sustainability, sports, and medicine.
  <br><br>
  <a href="https://www.linkedin.com/in/tim-ehrensperger-92a115216/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
